### ISSUE TITLE
Weird shadow when circles overlap

### ISSUE THREAD

**Issue by gmoshkin** [SimeonStylites/Hirjanov_labs#2]
![bug](https://user-images.githubusercontent.com/10168363/151669211-bc126e62-ad11-4532-9c58-c698d219536f.png)
Whenever the two circles overlap one of them seems to drop a funny shadow onto the other one. The shadow looks interesting but has a bit of an unexpected shape, as if the shadow is drawn using the upper circle's position from the previous frame.

I was just wondering if this is intentional or not

**Comment by SimeonStylites** [comment]
Thank you!
The shadow of the second circle (which is drawn to paint over its position from the previos frame) is drawn after drawing the first circle. So I will fix it

**Comment by SimeonStylites** [comment]
Fixed it!

**Comment by gmoshkin** [comment]
Thanks, the issue can now be closed!
